<?php


namespace App\Http\Controllers\Admin;


use App\Http\Controllers\Controller;
use App\Http\Controllers\Helpers\MrMessageHelper;
use App\Http\Models\MrBackup;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\DB;

class MrAdminBackUpController extends Controller
{
  public function index()
  {
    $out = array();
    $out['page_title'] = 'Бэкап БД';

    $file_migrations_list = DB::table('migrations')->pluck('migration')->toArray();

    $tables = array();
    foreach ($file_migrations_list as $item)
    {
      $class_name = '';
      foreach (explode('_', self::getTableNameFromFileName($item)) as $item_2)
      {
        if($item_2 == 'table')
        {
          continue;
        }

        $class_name .= substr_replace($item_2, mb_strtoupper(substr($item_2, 0, 1)), 0, 1);
      }

      if(class_exists("App\\Http\\Models\\" . $class_name))
      {
        $object = "App\\Http\\Models\\" . $class_name;
        $tables[] = array(
          'Name' => $object::$mr_table,
          'FileName' => $item,
          'has' => isset(self::$tables[$object::$mr_table]),
          'count_rows' => $object::getCount(),
        );
      }

    }

    $out['list'] = $tables;

    return View('Admin.mir_admin_backup_list')->with($out);
  }

  public static function getTableNameFromFileName(string $item)
  {
    return substr($item, 25, strlen($item));
  }

  public function SaveDataFromTable(string $table_name)
  {


    return back();
  }

  /**
   * Запись в таблицу
   *
   * @param string $table_name
   * @return RedirectResponse
   */
  public function RecoveryDataToTable(string $table_name)
  {
    if(isset(self::$tables[$table_name]))
    {
      MrBackup::recovery(self::$tables[$table_name], $table_name);
    }
    else
    {
      MrMessageHelper::SetMessage(false, 'Данных для восстановления в коде не найдены.');
    }

    return back();
  }

  public static $tables = array(
    'mr_currencies' => array(
      array('Code' => '784', 'TextCode' => 'AED', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Дирхам (ОАЭ)', 'Rounding' => '2', 'Description' => ''
      ),
      array('ID' => '2', 'Code' => '971', 'TextCode' => 'AFN', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Афгани', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '3', 'Code' => '008', 'TextCode' => 'ALL', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Лек', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '4', 'Code' => '051', 'TextCode' => 'AMD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Армянский драм', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '5', 'Code' => '532', 'TextCode' => 'ANG', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Нидерландский антильский гульден', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '6', 'Code' => '973', 'TextCode' => 'AOA', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Кванза', 'Rounding' => '2', 'Description' => 'Ангольская '),
      array('ID' => '7', 'Code' => '032', 'TextCode' => 'ARS', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Аргентинское песо', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '8', 'Code' => '040', 'TextCode' => 'ATS', 'DateFrom' => NULL, 'DateTo' => '2016-12-31 00:00:00', 'Name' => 'Австрийский шиллинг', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '9', 'Code' => '036', 'TextCode' => 'AUD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Австралийский доллар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '10', 'Code' => '533', 'TextCode' => 'AWG', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Арубанский флорин', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '11', 'Code' => '944', 'TextCode' => 'AZN', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Азербайджанский манат', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '12', 'Code' => '977', 'TextCode' => 'BAM', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Конвертируемая марка ', 'Rounding' => '2', 'Description' => '(Босния и Герцеговина)'),
      array('ID' => '13', 'Code' => '052', 'TextCode' => 'BBD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => ' Барбадосский доллар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '14', 'Code' => '050', 'TextCode' => 'BDT', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Така', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '15', 'Code' => '056', 'TextCode' => 'BEF', 'DateFrom' => NULL, 'DateTo' => '2016-12-31 00:00:00', 'Name' => 'Бельгийский франк', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '16', 'Code' => '975', 'TextCode' => 'BGN', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Болгарский лев', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '17', 'Code' => '048', 'TextCode' => 'BHD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Бахрейнский динар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '18', 'Code' => '108', 'TextCode' => 'BIF', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Бурундийский франк', 'Rounding' => '2', 'Description' => ' ', '
'),
      array('ID' => '19', 'Code' => '060', 'TextCode' => 'BMD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Бермудский доллар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '20', 'Code' => '096', 'TextCode' => 'BND', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Брунейский доллар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '21', 'Code' => '068', 'TextCode' => 'BOB', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Боливиано', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '22', 'Code' => '986', 'TextCode' => 'BRL', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Бразильский реал', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '23', 'Code' => '044', 'TextCode' => 'BSD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Багамский доллар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '24', 'Code' => '064', 'TextCode' => 'BTN', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Нгултрум', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '25', 'Code' => '072', 'TextCode' => 'BWP', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Пула', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '26', 'Code' => '974', 'TextCode' => 'BYR', 'DateFrom' => NULL, 'DateTo' => '2016-06-30 00:00:00', 'Name' => 'Белорусский рубль <1>', 'Rounding' => '0', 'Description' => '<1> Применяется для денежных средств, уплаченных до 30 июня 2016 г. включительно.'),
      array('ID' => '27', 'Code' => '933', 'TextCode' => 'BYN', 'DateFrom' => '2016-07-01 00:00:00', 'DateTo' => NULL, 'Name' => 'Белорусский рубль', 'Rounding' => '2', 'Description' => 'новый, с 1.07.2016'),
      array('ID' => '28', 'Code' => '084', 'TextCode' => 'BZD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Белизский доллар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '29', 'Code' => '124', 'TextCode' => 'CAD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Канадский доллар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '30', 'Code' => '976', 'TextCode' => 'CDF', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Конголезский франк', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '31', 'Code' => '756', 'TextCode' => 'CHF', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Швейцарский франк', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '32', 'Code' => '152', 'TextCode' => 'CLP', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Чилийское песо', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '33', 'Code' => '156', 'TextCode' => 'CNY', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Юань', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '34', 'Code' => '170', 'TextCode' => 'COP', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Колумбийское песо', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '35', 'Code' => '970', 'TextCode' => 'COU', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Единица реальной стоимости ', 'Rounding' => '2', 'Description' => '(Колумбия)'),
      array('ID' => '36', 'Code' => '188', 'TextCode' => 'CRC', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Костариканский колон', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '37', 'Code' => '931', 'TextCode' => 'CUC', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Конвертируемое песо', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '38', 'Code' => '192', 'TextCode' => 'CUP', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Кубинское песо', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '39', 'Code' => '132', 'TextCode' => 'CVE', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Эскудо  Кабо-Верде ', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '40', 'Code' => '203', 'TextCode' => 'CZK', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Чешская крона', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '41', 'Code' => '276', 'TextCode' => 'DEM', 'DateFrom' => NULL, 'DateTo' => '2016-12-31 00:00:00', 'Name' => 'Немецкая марка', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '42', 'Code' => '262', 'TextCode' => 'DJF', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Франк Джибути', 'Rounding' => '2', 'Description' => ' '),
      array('ID' => '43', 'Code' => '208', 'TextCode' => 'DKK', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Датская крона', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '44', 'Code' => '214', 'TextCode' => 'DOP', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Доминиканское песо', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '45', 'Code' => '012', 'TextCode' => 'DZD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Алжирский динар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '46', 'Code' => '233', 'TextCode' => 'EEK', 'DateFrom' => NULL, 'DateTo' => '2016-12-31 00:00:00', 'Name' => 'Эстонская крона', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '47', 'Code' => '818', 'TextCode' => 'EGP', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Египетский фунт', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '48', 'Code' => '232', 'TextCode' => 'ERN', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Накфа ', 'Rounding' => '2', 'Description' => '(Эритрея)'),
      array('ID' => '49', 'Code' => '724', 'TextCode' => 'ESP', 'DateFrom' => NULL, 'DateTo' => '2016-12-31 00:00:00', 'Name' => 'Испанская песета', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '50', 'Code' => '230', 'TextCode' => 'ETB', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Эфиопский быр', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '51', 'Code' => '978', 'TextCode' => 'EUR', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Евро', 'Rounding' => '2', 'Description' => '(Единая европейская валюта)

'),
      array('ID' => '52', 'Code' => '246', 'TextCode' => 'FIM', 'DateFrom' => NULL, 'DateTo' => '2016-12-31 00:00:00', 'Name' => 'Финляндская марка', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '53', 'Code' => '242', 'TextCode' => 'FJD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Доллар Фиджи', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '54', 'Code' => '238', 'TextCode' => 'FKP', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Фунт Фолклендских островов', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '55', 'Code' => '250', 'TextCode' => 'FRF', 'DateFrom' => NULL, 'DateTo' => '2016-12-31 00:00:00', 'Name' => 'Французский франк', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '56', 'Code' => '826', 'TextCode' => 'GBP', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Фунт стерлингов ', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '57', 'Code' => '981', 'TextCode' => 'GEL', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Лари', 'Rounding' => '2', 'Description' => 'Грузинский '),
      array('ID' => '58', 'Code' => '936', 'TextCode' => 'GHS', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Ганский седи', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '59', 'Code' => '292', 'TextCode' => 'GIP', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Гибралтарский фунт', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '60', 'Code' => '270', 'TextCode' => 'GMD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Даласи', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '61', 'Code' => '324', 'TextCode' => 'GNF', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Гвинейский франк', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '62', 'Code' => '300', 'TextCode' => 'GRD', 'DateFrom' => NULL, 'DateTo' => '2016-12-31 00:00:00', 'Name' => 'Греческая драхма', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '63', 'Code' => '320', 'TextCode' => 'GTQ', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Кетсаль', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '64', 'Code' => '328', 'TextCode' => 'GYD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Гайанский доллар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '65', 'Code' => '344', 'TextCode' => 'HKD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Гонконгский доллар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '66', 'Code' => '340', 'TextCode' => 'HNL', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Лемпира', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '67', 'Code' => '191', 'TextCode' => 'HRK', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Куна', 'Rounding' => '2', 'Description' => ' (Хорватия)'),
      array('ID' => '68', 'Code' => '332', 'TextCode' => 'HTG', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Гурд', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '69', 'Code' => '348', 'TextCode' => 'HUF', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Форинт', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '70', 'Code' => '360', 'TextCode' => 'IDR', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Рупия', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '71', 'Code' => '372', 'TextCode' => 'IEP', 'DateFrom' => NULL, 'DateTo' => '2016-12-31 00:00:00', 'Name' => 'Ирландский фунт', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '72', 'Code' => '376', 'TextCode' => 'ILS', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Новый израильский шекель', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '73', 'Code' => '356', 'TextCode' => 'INR', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Индийская рупия', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '74', 'Code' => '368', 'TextCode' => 'IQD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Иракский динар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '75', 'Code' => '364', 'TextCode' => 'IRR', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Иранский риал', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '76', 'Code' => '352', 'TextCode' => 'ISK', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Исландская крона', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '77', 'Code' => '380', 'TextCode' => 'ITL', 'DateFrom' => NULL, 'DateTo' => '2016-12-31 00:00:00', 'Name' => 'Итальянская лира', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '78', 'Code' => '388', 'TextCode' => 'JMD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Ямайский доллар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '79', 'Code' => '400', 'TextCode' => 'JOD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Иорданский динар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '80', 'Code' => '392', 'TextCode' => 'JPY', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Иена', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '81', 'Code' => '404', 'TextCode' => 'KES', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Кенийский шиллинг', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '82', 'Code' => '417', 'TextCode' => 'KGS', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Сом', 'Rounding' => '2', 'Description' => '(Киргизский)'),
      array('ID' => '83', 'Code' => '116', 'TextCode' => 'KHR', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Риель', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '84', 'Code' => '174', 'TextCode' => 'KMF', 'DateFrom' => NULL, 'DateTo' => '2017-10-12 00:00:00', 'Name' => 'Франк Комор', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '85', 'Code' => '408', 'TextCode' => 'KPW', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Северокорейская вона', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '86', 'Code' => '410', 'TextCode' => 'KRW', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Вона', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '87', 'Code' => '414', 'TextCode' => 'KWD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Кувейтский динар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '88', 'Code' => '136', 'TextCode' => 'KYD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Доллар островов Кайман', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '89', 'Code' => '398', 'TextCode' => 'KZT', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Тенге', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '90', 'Code' => '418', 'TextCode' => 'LAK', 'DateFrom' => NULL, 'DateTo' => '2017-10-12 00:00:00', 'Name' => 'Кип', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '91', 'Code' => '422', 'TextCode' => 'LBP', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Ливанский фунт', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '92', 'Code' => '144', 'TextCode' => 'LKR', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Шри-Ланкийская рупия', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '93', 'Code' => '430', 'TextCode' => 'LRD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Либерийский доллар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '94', 'Code' => '426', 'TextCode' => 'LSL', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Лоти ', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '95', 'Code' => '440', 'TextCode' => 'LTL', 'DateFrom' => NULL, 'DateTo' => '2018-06-23 00:00:00', 'Name' => 'Литовский лит <3>', 'Rounding' => '2', 'Description' => '<3> Не применяется с 1 января 2015 г.'),
      array('ID' => '96', 'Code' => '442', 'TextCode' => 'LUF', 'DateFrom' => NULL, 'DateTo' => '2016-12-31 00:00:00', 'Name' => 'Люксембургский франк', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '97', 'Code' => '428', 'TextCode' => 'LVL', 'DateFrom' => NULL, 'DateTo' => '2014-01-14 00:00:00', 'Name' => 'Латвийский лат <2>', 'Rounding' => '2', 'Description' => '<2> Не применяется с 15 января 2014 г.'),
      array('ID' => '98', 'Code' => '434', 'TextCode' => 'LYD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Ливийский динар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '99', 'Code' => '504', 'TextCode' => 'MAD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Марокканский дирхам', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '100', 'Code' => '498', 'TextCode' => 'MDL', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Молдавский лей', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '101', 'Code' => '969', 'TextCode' => 'MGA', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Малагасийский ариари', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '102', 'Code' => '807', 'TextCode' => 'MKD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Денар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '103', 'Code' => '104', 'TextCode' => 'MMK', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Кьят', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '104', 'Code' => '496', 'TextCode' => 'MNT', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Тугрик', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '105', 'Code' => '446', 'TextCode' => 'MOP', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Патака', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '106', 'Code' => '478', 'TextCode' => 'MRO', 'DateFrom' => NULL, 'DateTo' => '2018-06-23 00:00:00', 'Name' => 'Угия <4>', 'Rounding' => '2', 'Description' => 'Мавританская 
<4> Не применяется с 1 января 2018 г.'),
      array('ID' => '107', 'Code' => '480', 'TextCode' => 'MUR', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Маврикийская рупия', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '108', 'Code' => '462', 'TextCode' => 'MVR', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Руфия', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '109', 'Code' => '454', 'TextCode' => 'MWK', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Малавийская квача', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '110', 'Code' => '484', 'TextCode' => 'MXN', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Мексиканское песо', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '111', 'Code' => '458', 'TextCode' => 'MYR', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Малайзийский ринггит', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '112', 'Code' => '943', 'TextCode' => 'MZN', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Мозамбикский метикал', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '113', 'Code' => '516', 'TextCode' => 'NAD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Доллар Намибии', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '114', 'Code' => '566', 'TextCode' => 'NGN', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Найра', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '115', 'Code' => '558', 'TextCode' => 'NIO', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Золотая кордоба', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '116', 'Code' => '528', 'TextCode' => 'NLG', 'DateFrom' => NULL, 'DateTo' => '2016-12-31 00:00:00', 'Name' => 'Нидерландский гульден', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '117', 'Code' => '578', 'TextCode' => 'NOK', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Норвежская крона', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '118', 'Code' => '524', 'TextCode' => 'NPR', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Непальская рупия', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '119', 'Code' => '554', 'TextCode' => 'NZD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Новозеландский доллар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '120', 'Code' => '512', 'TextCode' => 'OMR', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Оманский риал', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '121', 'Code' => '590', 'TextCode' => 'PAB', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Бальбоа', 'Rounding' => '2', 'Description' => 'Панамский '),
      array('ID' => '122', 'Code' => '604', 'TextCode' => 'PEN', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Соль', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '123', 'Code' => '598', 'TextCode' => 'PGK', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Кина', 'Rounding' => '2', 'Description' => ' Папуа-Новой Гвинеи'),
      array('ID' => '124', 'Code' => '608', 'TextCode' => 'PHP', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Филиппинское песо', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '125', 'Code' => '586', 'TextCode' => 'PKR', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Пакистанская рупия', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '126', 'Code' => '985', 'TextCode' => 'PLN', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Злотый', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '127', 'Code' => '620', 'TextCode' => 'PTE', 'DateFrom' => NULL, 'DateTo' => '2016-12-31 00:00:00', 'Name' => 'Португальский эскудо', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '128', 'Code' => '600', 'TextCode' => 'PYG', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Гуарани', 'Rounding' => '2', 'Description' => 'Парагвайский '),
      array('ID' => '129', 'Code' => '634', 'TextCode' => 'QAR', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Катарский риал', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '130', 'Code' => '946', 'TextCode' => 'RON', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Румынский Лей ', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '131', 'Code' => '941', 'TextCode' => 'RSD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Сербский динар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '132', 'Code' => '643', 'TextCode' => 'RUB', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Российский рубль', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '133', 'Code' => '646', 'TextCode' => 'RWF', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Франк Руанды', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '134', 'Code' => '682', 'TextCode' => 'SAR', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Саудовский риял', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '135', 'Code' => '090', 'TextCode' => 'SBD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Доллар Соломоновых островов', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '136', 'Code' => '690', 'TextCode' => 'SCR', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Сейшельская рупия', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '137', 'Code' => '938', 'TextCode' => 'SDG', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Суданский фунт', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '138', 'Code' => '752', 'TextCode' => 'SEK', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Шведская крона', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '139', 'Code' => '702', 'TextCode' => 'SGD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Сингапурский доллар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '140', 'Code' => '654', 'TextCode' => 'SHP', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Фунт Святой Елены ', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '141', 'Code' => '705', 'TextCode' => 'SIT', 'DateFrom' => NULL, 'DateTo' => '2016-12-31 00:00:00', 'Name' => 'Толар (Словения)', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '142', 'Code' => '694', 'TextCode' => 'SLL', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => ' Леоне', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '143', 'Code' => '706', 'TextCode' => 'SOS', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Сомалийский шиллинг', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '144', 'Code' => '968', 'TextCode' => 'SRD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Суринамский доллар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '145', 'Code' => '678', 'TextCode' => 'STD', 'DateFrom' => NULL, 'DateTo' => '2018-06-23 00:00:00', 'Name' => 'Добра <4>', 'Rounding' => '2', 'Description' => '<4> Не применяется с 1 января 2018 г.'),
      array('ID' => '146', 'Code' => '222', 'TextCode' => 'SVC', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Сальвадорский колон', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '147', 'Code' => '760', 'TextCode' => 'SYP', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Сирийский фунт', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '148', 'Code' => '748', 'TextCode' => 'SZL', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Лилангени', 'Rounding' => '2', 'Description' => 'Свазилендский'),
      array('ID' => '149', 'Code' => '764', 'TextCode' => 'THB', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Бат', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '150', 'Code' => '972', 'TextCode' => 'TJS', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Сомони', 'Rounding' => '2', 'Description' => 'Таджикский '),
      array('ID' => '151', 'Code' => '934', 'TextCode' => 'TMT', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Новый туркменский манат', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '152', 'Code' => '788', 'TextCode' => 'TND', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Тунисский динар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '153', 'Code' => '776', 'TextCode' => 'TOP', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Паанга', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '154', 'Code' => '949', 'TextCode' => 'TRY', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Турецкая лира', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '155', 'Code' => '780', 'TextCode' => 'TTD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Доллар Тринидада и Тобаго', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '156', 'Code' => '901', 'TextCode' => 'TWD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Новый Тайваньский доллар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '157', 'Code' => '834', 'TextCode' => 'TZS', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Танзанийский шиллинг', 'Rounding' => '2', 'Description' => '

'),
      array('ID' => '158', 'Code' => '980', 'TextCode' => 'UAH', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Гривна', 'Rounding' => '2', 'Description' => 'Украинская '),
      array('ID' => '159', 'Code' => '800', 'TextCode' => 'UGX', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Угандийский шиллинг', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '160', 'Code' => '840', 'TextCode' => 'USD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Доллар США', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '161', 'Code' => '940', 'TextCode' => 'UYI', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Уругвайское песо в индексированных единицах', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '162', 'Code' => '858', 'TextCode' => 'UYU', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Уругвайское песо', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '163', 'Code' => '860', 'TextCode' => 'UZS', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Узбекский Сум', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '164', 'Code' => '937', 'TextCode' => 'VEF', 'DateFrom' => NULL, 'DateTo' => '2019-06-15 00:00:00', 'Name' => 'Боливар <5>', 'Rounding' => '2', 'Description' => '<5> Не применяется с 20 августа 2018 г.'),
      array('ID' => '165', 'Code' => '704', 'TextCode' => 'VND', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Донг', 'Rounding' => '2', 'Description' => 'Ветнамский '),
      array('ID' => '166', 'Code' => '548', 'TextCode' => 'VUV', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Вату', 'Rounding' => '2', 'Description' => 'Республики  Вануату '),
      array('ID' => '167', 'Code' => '882', 'TextCode' => 'WST', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Тала', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '168', 'Code' => '950', 'TextCode' => 'XAF', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Франк КФА ВЕАС  <6>', 'Rounding' => '2', 'Description' => '<6>- денежная единица Банка государств Центральной Африки'),
      array('ID' => '169', 'Code' => '951', 'TextCode' => 'XCD', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Восточно-карибский доллар', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '170', 'Code' => '960', 'TextCode' => 'XDR', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'СДР (Специальные права заимствования)', 'Rounding' => '2', 'Description' => ' Международный валютный фонд'),
      array('ID' => '171', 'Code' => '952', 'TextCode' => 'XOF', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Франк КФА BCEAO <7>', 'Rounding' => '2', 'Description' => '<7> - денежная единица Центрального Банка государств Западной Африки.'),
      array('ID' => '172', 'Code' => '953', 'TextCode' => 'XPF', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => ' Франк КФП', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '173', 'Code' => '886', 'TextCode' => 'YER', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Йеменский риал', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '174', 'Code' => '710', 'TextCode' => 'ZAR', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Рэнд', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '175', 'Code' => '967', 'TextCode' => 'ZMW', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Замбийская квача', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '176', 'Code' => '932', 'TextCode' => 'ZWL', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Доллар Зимбабве', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '177', 'Code' => '728', 'TextCode' => 'SSP', 'DateFrom' => NULL, 'DateTo' => NULL, 'Name' => 'Южносуданский фунт', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '178', 'Code' => '174', 'TextCode' => 'KMF', 'DateFrom' => '2017-10-13 00:00:00', 'DateTo' => NULL, 'Name' => 'Коморский франк', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '179', 'Code' => '418', 'TextCode' => 'LAK', 'DateFrom' => '2017-10-13 00:00:00', 'DateTo' => NULL, 'Name' => 'Лаосский кип', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '180', 'Code' => '929', 'TextCode' => 'MRU', 'DateFrom' => '2018-06-24 00:00:00', 'DateTo' => NULL, 'Name' => 'Угия', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '181', 'Code' => '930', 'TextCode' => 'STN', 'DateFrom' => '2018-06-24 00:00:00', 'DateTo' => NULL, 'Name' => 'Добра', 'Rounding' => '2', 'Description' => ''),
      array('ID' => '182', 'Code' => '928', 'TextCode' => 'VES', 'DateFrom' => '2019-06-16 00:00:00', 'DateTo' => NULL, 'Name' => 'Боливар Соберано', 'Rounding' => '2', 'Description' => NULL)
    ),
    'mr_country' => array(
      array('1', 'Andorra', 'AD', 'AND', '20', 'Andorra la Vella', 'EU'),
      array('1', 'Andorra', 'AD', 'AND', '20', 'Andorra la Vella', 'EU'),
      array('2', 'United Arab Emirates', 'AE', 'ARE', '784', 'Abu Dhabi', 'AS'),
      array('2', 'United Arab Emirates', 'AE', 'ARE', '784', 'Abu Dhabi', 'AS'),
      array('3', 'Afghanistan', 'AF', 'AFG', '4', 'Kabul', 'AS'),
      array('3', 'Afghanistan', 'AF', 'AFG', '4', 'Kabul', 'AS'),
      array('4', 'Antigua and Barbuda', 'AG', 'ATG', '28', 'St. John`s', 'NA'),
      array('4', 'Antigua and Barbuda', 'AG', 'ATG', '28', 'St. John`s', 'NA'),
      array('5', 'Anguilla', 'AI', 'AIA', '660', 'The Valley', 'NA'),
      array('5', 'Anguilla', 'AI', 'AIA', '660', 'The Valley', 'NA'),
      array('6', 'Albania', 'AL', 'ALB', '8', 'Tirana', 'EU'),
      array('6', 'Albania', 'AL', 'ALB', '8', 'Tirana', 'EU'),
      array('7', 'Armenia', 'AM', 'ARM', '51', 'Yerevan', 'AS'),
      array('7', 'Armenia', 'AM', 'ARM', '51', 'Yerevan', 'AS'),
      array('8', 'Netherlands Antilles', 'AN', 'ANT', '530', 'Willemstad', 'NA'),
      array('8', 'Netherlands Antilles', 'AN', 'ANT', '530', 'Willemstad', 'NA'),
      array('9', 'Angola', 'AO', 'AGO', '24', 'Luanda', 'AF'),
      array('9', 'Angola', 'AO', 'AGO', '24', 'Luanda', 'AF'),
      array('10', 'Antarctica', 'AQ', 'ATA', '10', 'Antarctica', 'AN'),
      array('10', 'Antarctica', 'AQ', 'ATA', '10', 'Antarctica', 'AN'),
      array('11', 'Argentina', 'AR', 'ARG', '32', 'Buenos Aires', 'SA'),
      array('11', 'Argentina', 'AR', 'ARG', '32', 'Buenos Aires', 'SA'),
      array('12', 'American Samoa', 'AS', 'ASM', '16', 'Pago Pago', 'OC'),
      array('12', 'American Samoa', 'AS', 'ASM', '16', 'Pago Pago', 'OC'),
      array('13', 'Austria', 'AT', 'AUT', '40', 'Vienna', 'EU'),
      array('13', 'Austria', 'AT', 'AUT', '40', 'Vienna', 'EU'),
      array('14', 'Australia', 'AU', 'AUS', '36', 'Canberra', 'OC'),
      array('14', 'Australia', 'AU', 'AUS', '36', 'Canberra', 'OC'),
      array('15', 'Aruba', 'AW', 'ABW', '533', 'Oranjestad', 'NA'),
      array('15', 'Aruba', 'AW', 'ABW', '533', 'Oranjestad', 'NA'),
      array('16', 'Azerbaijan', 'AZ', 'AZE', '31', 'Baku', 'AS'),
      array('16', 'Azerbaijan', 'AZ', 'AZE', '31', 'Baku', 'AS'),
      array('17', 'Bosnia and Herzegovina', 'BA', 'BIH', '70', 'Sarajevo', 'EU'),
      array('17', 'Bosnia and Herzegovina', 'BA', 'BIH', '70', 'Sarajevo', 'EU'),
      array('18', 'Barbados', 'BB', 'BRB', '52', 'Bridgetown', 'NA'),
      array('18', 'Barbados', 'BB', 'BRB', '52', 'Bridgetown', 'NA'),
      array('19', 'Bangladesh', 'BD', 'BGD', '50', 'Dhaka', 'AS'),
      array('19', 'Bangladesh', 'BD', 'BGD', '50', 'Dhaka', 'AS'),
      array('20', 'Belgium', 'BE', 'BEL', '56', 'Brussels', 'EU'),
      array('20', 'Belgium', 'BE', 'BEL', '56', 'Brussels', 'EU'),
      array('21', 'Burkina Faso', 'BF', 'BFA', '854', 'Ouagadougou', 'AF'),
      array('21', 'Burkina Faso', 'BF', 'BFA', '854', 'Ouagadougou', 'AF'),
      array('22', 'Bulgaria', 'BG', 'BGR', '100', 'Sofia', 'EU'),
      array('22', 'Bulgaria', 'BG', 'BGR', '100', 'Sofia', 'EU'),
      array('23', 'Bahrain', 'BH', 'BHR', '48', 'Manama', 'AS'),
      array('23', 'Bahrain', 'BH', 'BHR', '48', 'Manama', 'AS'),
      array('24', 'Burundi', 'BI', 'BDI', '108', 'Gitega', 'AF'),
      array('24', 'Burundi', 'BI', 'BDI', '108', 'Gitega', 'AF'),
      array('25', 'Benin', 'BJ', 'BEN', '204', 'Porto-Novo', 'AF'),
      array('25', 'Benin', 'BJ', 'BEN', '204', 'Porto-Novo', 'AF'),
      array('26', 'Saint Barth?lemy', 'BL', 'BLM', '652', 'Gustavia', 'NA'),
      array('26', 'Saint Barth?lemy', 'BL', 'BLM', '652', 'Gustavia', 'NA'),
      array('27', 'Bermuda', 'BM', 'BMU', '60', 'Hamilton', 'NA'),
      array('27', 'Bermuda', 'BM', 'BMU', '60', 'Hamilton', 'NA'),
      array('28', 'Brunei', 'BN', 'BRN', '96', 'Bandar Seri Begawan', 'AS'),
      array('28', 'Brunei', 'BN', 'BRN', '96', 'Bandar Seri Begawan', 'AS'),
      array('29', 'Bolivia', 'BO', 'BOL', '68', 'Sucre', 'SA'),
      array('29', 'Bolivia', 'BO', 'BOL', '68', 'Sucre', 'SA'),
      array('30', 'Brazil', 'BR', 'BRA', '76', 'Brasilia', 'SA'),
      array('30', 'Brazil', 'BR', 'BRA', '76', 'Brasilia', 'SA'),
      array('31', 'Bahamas', 'BS', 'BHS', '44', 'Nassau', 'NA'),
      array('31', 'Bahamas', 'BS', 'BHS', '44', 'Nassau', 'NA'),
      array('32', 'Bhutan', 'BT', 'BTN', '64', 'Thimphu', 'AS'),
      array('32', 'Bhutan', 'BT', 'BTN', '64', 'Thimphu', 'AS'),
      array('33', 'Bouvet Island', 'BV', 'BVT', '74', 'Bouvet Island', 'AN'),
      array('33', 'Bouvet Island', 'BV', 'BVT', '74', 'Bouvet Island', 'AN'),
      array('34', 'Botswana', 'BW', 'BWA', '72', 'Gaborone', 'AF'),
      array('34', 'Botswana', 'BW', 'BWA', '72', 'Gaborone', 'AF'),
      array('35', 'Belarus', 'BY', 'BLR', '112', 'Minsk', 'EU'),
      array('35', 'Belarus', 'BY', 'BLR', '112', 'Minsk', 'EU'),
      array('36', 'Belize', 'BZ', 'BLZ', '84', 'Belmopan', 'NA'),
      array('36', 'Belize', 'BZ', 'BLZ', '84', 'Belmopan', 'NA'),
      array('37', 'Canada', 'CA', 'CAN', '124', 'Ottawa', 'NA'),
      array('37', 'Canada', 'CA', 'CAN', '124', 'Ottawa', 'NA'),
      array('38', 'Cocos [Keeling] Islands', 'CC', 'CCK', '166', 'West Island', 'AS'),
      array('38', 'Cocos [Keeling] Islands', 'CC', 'CCK', '166', 'West Island', 'AS'),
      array('39', 'DR Congo', 'CD', 'COD', '180', 'Kinshasa', 'AF'),
      array('39', 'DR Congo', 'CD', 'COD', '180', 'Kinshasa', 'AF'),
      array('40', 'Central African Republic', 'CF', 'CAF', '140', 'Bangui', 'AF'),
      array('40', 'Central African Republic', 'CF', 'CAF', '140', 'Bangui', 'AF'),
      array('41', 'Congo Republic', 'CG', 'COG', '178', 'Brazzaville', 'AF'),
      array('41', 'Congo Republic', 'CG', 'COG', '178', 'Brazzaville', 'AF'),
      array('42', 'Switzerland', 'CH', 'CHE', '756', 'Bern', 'EU'),
      array('42', 'Switzerland', 'CH', 'CHE', '756', 'Bern', 'EU'),
      array('43', 'Ivory Coast', 'CI', 'CIV', '384', 'Yamoussoukro', 'AF'),
      array('43', 'Ivory Coast', 'CI', 'CIV', '384', 'Yamoussoukro', 'AF'),
      array('44', 'Cook Islands', 'CK', 'COK', '184', 'Avarua', 'OC'),
      array('44', 'Cook Islands', 'CK', 'COK', '184', 'Avarua', 'OC'),
      array('45', 'Chile', 'CL', 'CHL', '152', 'Santiago', 'SA'),
      array('45', 'Chile', 'CL', 'CHL', '152', 'Santiago', 'SA'),
      array('46', 'Cameroon', 'CM', 'CMR', '120', 'Yaounde', 'AF'),
      array('46', 'Cameroon', 'CM', 'CMR', '120', 'Yaounde', 'AF'),
      array('47', 'China', 'CN', 'CHN', '156', 'Beijing', 'AS'),
      array('47', 'China', 'CN', 'CHN', '156', 'Beijing', 'AS'),
      array('48', 'Colombia', 'CO', 'COL', '170', 'Bogota', 'SA'),
      array('48', 'Colombia', 'CO', 'COL', '170', 'Bogota', 'SA'),
      array('49', 'Costa Rica', 'CR', 'CRI', '188', 'San Jose', 'NA'),
      array('49', 'Costa Rica', 'CR', 'CRI', '188', 'San Jose', 'NA'),
      array('50', 'Serbia and Montenegro', 'CS', 'SCG', '891', 'Belgrade', 'EU'),
      array('50', 'Serbia and Montenegro', 'CS', 'SCG', '891', 'Belgrade', 'EU'),
      array('51', 'Cuba', 'CU', 'CUB', '192', 'Havana', 'NA'),
      array('51', 'Cuba', 'CU', 'CUB', '192', 'Havana', 'NA'),
      array('52', 'Cabo Verde', 'CV', 'CPV', '132', 'Praia', 'AF'),
      array('52', 'Cabo Verde', 'CV', 'CPV', '132', 'Praia', 'AF'),
      array('53', 'Cura?ao', 'CW', 'CUW', '531', 'Willemstad', 'NA'),
      array('53', 'Cura?ao', 'CW', 'CUW', '531', 'Willemstad', 'NA'),
      array('54', 'Christmas Island', 'CX', 'CXR', '162', 'Flying Fish Cove', 'OC'),
      array('54', 'Christmas Island', 'CX', 'CXR', '162', 'Flying Fish Cove', 'OC'),
      array('55', 'Cyprus', 'CY', 'CYP', '196', 'Nicosia', 'EU'),
      array('55', 'Cyprus', 'CY', 'CYP', '196', 'Nicosia', 'EU'),
      array('56', 'Czechia', 'CZ', 'CZE', '203', 'Prague', 'EU'),
      array('56', 'Czechia', 'CZ', 'CZE', '203', 'Prague', 'EU'),
      array('57', 'Germany', 'DE', 'DEU', '276', 'Berlin', 'EU'),
      array('57', 'Germany', 'DE', 'DEU', '276', 'Berlin', 'EU'),
      array('58', 'Djibouti', 'DJ', 'DJI', '262', 'Djibouti', 'AF'),
      array('58', 'Djibouti', 'DJ', 'DJI', '262', 'Djibouti', 'AF'),
      array('59', 'Denmark', 'DK', 'DNK', '208', 'Copenhagen', 'EU'),
      array('59', 'Denmark', 'DK', 'DNK', '208', 'Copenhagen', 'EU'),
      array('60', 'Dominica', 'DM', 'DMA', '212', 'Roseau', 'NA'),
      array('60', 'Dominica', 'DM', 'DMA', '212', 'Roseau', 'NA'),
      array('61', 'Dominican Republic', 'DO', 'DOM', '214', 'Santo Domingo', 'NA'),
      array('61', 'Dominican Republic', 'DO', 'DOM', '214', 'Santo Domingo', 'NA'),
      array('62', 'Algeria', 'DZ', 'DZA', '12', 'Algiers', 'AF'),
      array('62', 'Algeria', 'DZ', 'DZA', '12', 'Algiers', 'AF'),
      array('63', 'Ecuador', 'EC', 'ECU', '218', 'Quito', 'SA'),
      array('63', 'Ecuador', 'EC', 'ECU', '218', 'Quito', 'SA'),
      array('64', 'Estonia', 'EE', 'EST', '233', 'Tallinn', 'EU'),
      array('64', 'Estonia', 'EE', 'EST', '233', 'Tallinn', 'EU'),
      array('65', 'Egypt', 'EG', 'EGY', '818', 'Cairo', 'AF'),
      array('65', 'Egypt', 'EG', 'EGY', '818', 'Cairo', 'AF'),
      array('66', 'Western Sahara', 'EH', 'ESH', '732', 'El-Aaiun', 'AF'),
      array('66', 'Western Sahara', 'EH', 'ESH', '732', 'El-Aaiun', 'AF'),
      array('67', 'Eritrea', 'ER', 'ERI', '232', 'Asmara', 'AF'),
      array('67', 'Eritrea', 'ER', 'ERI', '232', 'Asmara', 'AF'),
      array('68', 'Spain', 'ES', 'ESP', '724', 'Madrid', 'EU'),
      array('68', 'Spain', 'ES', 'ESP', '724', 'Madrid', 'EU'),
      array('69', 'Ethiopia', 'ET', 'ETH', '231', 'Addis Ababa', 'AF'),
      array('69', 'Ethiopia', 'ET', 'ETH', '231', 'Addis Ababa', 'AF'),
      array('70', 'Finland', 'FI', 'FIN', '246', 'Helsinki', 'EU'),
      array('70', 'Finland', 'FI', 'FIN', '246', 'Helsinki', 'EU'),
      array('71', 'Fiji', 'FJ', 'FJI', '242', 'Suva', 'OC'),
      array('71', 'Fiji', 'FJ', 'FJI', '242', 'Suva', 'OC'),
      array('72', 'Falkland Islands', 'FK', 'FLK', '238', 'Stanley', 'SA'),
      array('72', 'Falkland Islands', 'FK', 'FLK', '238', 'Stanley', 'SA'),
      array('73', 'Micronesia', 'FM', 'FSM', '583', 'Palikir', 'OC'),
      array('73', 'Micronesia', 'FM', 'FSM', '583', 'Palikir', 'OC'),
      array('74', 'Faroe Islands', 'FO', 'FRO', '234', 'Torshavn', 'EU'),
      array('74', 'Faroe Islands', 'FO', 'FRO', '234', 'Torshavn', 'EU'),
      array('75', 'France', 'FR', 'FRA', '250', 'Paris', 'EU'),
      array('75', 'France', 'FR', 'FRA', '250', 'Paris', 'EU'),
      array('76', 'Gabon', 'GA', 'GAB', '266', 'Libreville', 'AF'),
      array('76', 'Gabon', 'GA', 'GAB', '266', 'Libreville', 'AF'),
      array('77', 'United Kingdom', 'GB', 'GBR', '826', 'London', 'EU'),
      array('77', 'United Kingdom', 'GB', 'GBR', '826', 'London', 'EU'),
      array('78', 'Grenada', 'GD', 'GRD', '308', 'St. George`s', 'NA'),
      array('78', 'Grenada', 'GD', 'GRD', '308', 'St. George`s', 'NA'),
      array('79', 'Georgia', 'GE', 'GEO', '268', 'Tbilisi', 'AS'),
      array('79', 'Georgia', 'GE', 'GEO', '268', 'Tbilisi', 'AS'),
      array('80', 'French Guiana', 'GF', 'GUF', '254', 'Cayenne', 'SA'),
      array('80', 'French Guiana', 'GF', 'GUF', '254', 'Cayenne', 'SA'),
      array('81', 'Guernsey', 'GG', 'GGY', '831', 'St Peter Port', 'EU'),
      array('81', 'Guernsey', 'GG', 'GGY', '831', 'St Peter Port', 'EU'),
      array('82', 'Ghana', 'GH', 'GHA', '288', 'Accra', 'AF'),
      array('82', 'Ghana', 'GH', 'GHA', '288', 'Accra', 'AF'),
      array('83', 'Gibraltar', 'GI', 'GIB', '292', 'Gibraltar', 'EU'),
      array('83', 'Gibraltar', 'GI', 'GIB', '292', 'Gibraltar', 'EU'),
      array('84', 'Greenland', 'GL', 'GRL', '304', 'Nuuk', 'NA'),
      array('84', 'Greenland', 'GL', 'GRL', '304', 'Nuuk', 'NA'),
      array('85', 'Gambia', 'GM', 'GMB', '270', 'Banjul', 'AF'),
      array('85', 'Gambia', 'GM', 'GMB', '270', 'Banjul', 'AF'),
      array('86', 'Guinea', 'GN', 'GIN', '324', 'Conakry', 'AF'),
      array('86', 'Guinea', 'GN', 'GIN', '324', 'Conakry', 'AF'),
      array('87', 'Guadeloupe', 'GP', 'GLP', '312', 'Basse-Terre', 'NA'),
      array('87', 'Guadeloupe', 'GP', 'GLP', '312', 'Basse-Terre', 'NA'),
      array('88', 'Equatorial Guinea', 'GQ', 'GNQ', '226', 'Malabo', 'AF'),
      array('88', 'Equatorial Guinea', 'GQ', 'GNQ', '226', 'Malabo', 'AF'),
      array('89', 'Greece', 'GR', 'GRC', '300', 'Athens', 'EU'),
      array('89', 'Greece', 'GR', 'GRC', '300', 'Athens', 'EU'),
      array('90', 'South Georgia and South Sandwich Islands', 'GS', 'SGS', '239', 'Grytviken', 'AN'),
      array('90', 'South Georgia and South Sandwich Islands', 'GS', 'SGS', '239', 'Grytviken', 'AN'),
      array('91', 'Guatemala', 'GT', 'GTM', '320', 'Guatemala City', 'NA'),
      array('91', 'Guatemala', 'GT', 'GTM', '320', 'Guatemala City', 'NA'),
      array('92', 'Guam', 'GU', 'GUM', '316', 'Hagatna', 'OC'),
      array('92', 'Guam', 'GU', 'GUM', '316', 'Hagatna', 'OC'),
      array('93', 'Guinea-Bissau', 'GW', 'GNB', '624', 'Bissau', 'AF'),
      array('93', 'Guinea-Bissau', 'GW', 'GNB', '624', 'Bissau', 'AF'),
      array('94', 'Guyana', 'GY', 'GUY', '328', 'Georgetown', 'SA'),
      array('94', 'Guyana', 'GY', 'GUY', '328', 'Georgetown', 'SA'),
      array('95', 'Hong Kong', 'HK', 'HKG', '344', 'Hong Kong', 'AS'),
      array('95', 'Hong Kong', 'HK', 'HKG', '344', 'Hong Kong', 'AS'),
      array('96', 'Heard Island and McDonald Islands', 'HM', 'HMD', '334', 'Heard Island and McDonald Islands', 'AN'),
      array('96', 'Heard Island and McDonald Islands', 'HM', 'HMD', '334', 'Heard Island and McDonald Islands', 'AN'),
      array('97', 'Honduras', 'HN', 'HND', '340', 'Tegucigalpa', 'NA'),
      array('97', 'Honduras', 'HN', 'HND', '340', 'Tegucigalpa', 'NA'),
      array('98', 'Croatia', 'HR', 'HRV', '191', 'Zagreb', 'EU'),
      array('98', 'Croatia', 'HR', 'HRV', '191', 'Zagreb', 'EU'),
      array('99', 'Haiti', 'HT', 'HTI', '332', 'Port-au-Prince', 'NA'),
      array('99', 'Haiti', 'HT', 'HTI', '332', 'Port-au-Prince', 'NA'),
      array('100', 'Hungary', 'HU', 'HUN', '348', 'Budapest', 'EU'),
      array('100', 'Hungary', 'HU', 'HUN', '348', 'Budapest', 'EU'),
      array('101', 'Indonesia', 'ID', 'IDN', '360', 'Jakarta', 'AS'),
      array('101', 'Indonesia', 'ID', 'IDN', '360', 'Jakarta', 'AS'),
      array('102', 'Ireland', 'IE', 'IRL', '372', 'Dublin', 'EU'),
      array('102', 'Ireland', 'IE', 'IRL', '372', 'Dublin', 'EU'),
      array('103', 'Israel', 'IL', 'ISR', '376', 'Jerusalem', 'AS'),
      array('103', 'Israel', 'IL', 'ISR', '376', 'Jerusalem', 'AS'),
      array('104', 'Isle of Man', 'IM', 'IMN', '833', 'Douglas', 'EU'),
      array('104', 'Isle of Man', 'IM', 'IMN', '833', 'Douglas', 'EU'),
      array('105', 'India', 'IN', 'IND', '356', 'New Delhi', 'AS'),
      array('105', 'India', 'IN', 'IND', '356', 'New Delhi', 'AS'),
      array('106', 'British Indian Ocean Territory', 'IO', 'IOT', '86', 'Diego Garcia', 'AS'),
      array('106', 'British Indian Ocean Territory', 'IO', 'IOT', '86', 'Diego Garcia', 'AS'),
      array('107', 'Iraq', 'IQ', 'IRQ', '368', 'Baghdad', 'AS'),
      array('107', 'Iraq', 'IQ', 'IRQ', '368', 'Baghdad', 'AS'),
      array('108', 'Iran', 'IR', 'IRN', '364', 'Tehran', 'AS'),
      array('108', 'Iran', 'IR', 'IRN', '364', 'Tehran', 'AS'),
      array('109', 'Iceland', 'IS', 'ISL', '352', 'Reykjavik', 'EU'),
      array('109', 'Iceland', 'IS', 'ISL', '352', 'Reykjavik', 'EU'),
      array('110', 'Italy', 'IT', 'ITA', '380', 'Rome', 'EU'),
      array('110', 'Italy', 'IT', 'ITA', '380', 'Rome', 'EU'),
      array('111', 'Jersey', 'JE', 'JEY', '832', 'Saint Helier', 'EU'),
      array('111', 'Jersey', 'JE', 'JEY', '832', 'Saint Helier', 'EU'),
      array('112', 'Jamaica', 'JM', 'JAM', '388', 'Kingston', 'NA'),
      array('112', 'Jamaica', 'JM', 'JAM', '388', 'Kingston', 'NA'),
      array('113', 'Jordan', 'JO', 'JOR', '400', 'Amman', 'AS'),
      array('113', 'Jordan', 'JO', 'JOR', '400', 'Amman', 'AS'),
      array('114', 'Japan', 'JP', 'JPN', '392', 'Tokyo', 'AS'),
      array('114', 'Japan', 'JP', 'JPN', '392', 'Tokyo', 'AS'),
      array('115', 'Kenya', 'KE', 'KEN', '404', 'Nairobi', 'AF'),
      array('115', 'Kenya', 'KE', 'KEN', '404', 'Nairobi', 'AF'),
      array('116', 'Kyrgyzstan', 'KG', 'KGZ', '417', 'Bishkek', 'AS'),
      array('116', 'Kyrgyzstan', 'KG', 'KGZ', '417', 'Bishkek', 'AS'),
      array('117', 'Cambodia', 'KH', 'KHM', '116', 'Phnom Penh', 'AS'),
      array('117', 'Cambodia', 'KH', 'KHM', '116', 'Phnom Penh', 'AS'),
      array('118', 'Kiribati', 'KI', 'KIR', '296', 'Tarawa', 'OC'),
      array('118', 'Kiribati', 'KI', 'KIR', '296', 'Tarawa', 'OC'),
      array('119', 'Comoros', 'KM', 'COM', '174', 'Moroni', 'AF'),
      array('119', 'Comoros', 'KM', 'COM', '174', 'Moroni', 'AF'),
      array('120', 'St Kitts and Nevis', 'KN', 'KNA', '659', 'Basseterre', 'NA'),
      array('120', 'St Kitts and Nevis', 'KN', 'KNA', '659', 'Basseterre', 'NA'),
      array('121', 'North Korea', 'KP', 'PRK', '408', 'Pyongyang', 'AS'),
      array('121', 'North Korea', 'KP', 'PRK', '408', 'Pyongyang', 'AS'),
      array('122', 'South Korea', 'KR', 'KOR', '410', 'Seoul', 'AS'),
      array('122', 'South Korea', 'KR', 'KOR', '410', 'Seoul', 'AS'),
      array('123', 'Kuwait', 'KW', 'KWT', '414', 'Kuwait City', 'AS'),
      array('123', 'Kuwait', 'KW', 'KWT', '414', 'Kuwait City', 'AS'),
      array('124', 'Cayman Islands', 'KY', 'CYM', '136', 'George Town', 'NA'),
      array('124', 'Cayman Islands', 'KY', 'CYM', '136', 'George Town', 'NA'),
      array('125', 'Kazakhstan', 'KZ', 'KAZ', '398', 'Nur-Sultan', 'AS'),
      array('125', 'Kazakhstan', 'KZ', 'KAZ', '398', 'Nur-Sultan', 'AS'),
      array('126', 'Laos', 'LA', 'LAO', '418', 'Vientiane', 'AS'),
      array('126', 'Laos', 'LA', 'LAO', '418', 'Vientiane', 'AS'),
      array('127', 'Lebanon', 'LB', 'LBN', '422', 'Beirut', 'AS'),
      array('127', 'Lebanon', 'LB', 'LBN', '422', 'Beirut', 'AS'),
      array('128', 'Saint Lucia', 'LC', 'LCA', '662', 'Castries', 'NA'),
      array('128', 'Saint Lucia', 'LC', 'LCA', '662', 'Castries', 'NA'),
      array('129', 'Liechtenstein', 'LI', 'LIE', '438', 'Vaduz', 'EU'),
      array('129', 'Liechtenstein', 'LI', 'LIE', '438', 'Vaduz', 'EU'),
      array('130', 'Sri Lanka', 'LK', 'LKA', '144', 'Colombo', 'AS'),
      array('130', 'Sri Lanka', 'LK', 'LKA', '144', 'Colombo', 'AS'),
      array('131', 'Liberia', 'LR', 'LBR', '430', 'Monrovia', 'AF'),
      array('131', 'Liberia', 'LR', 'LBR', '430', 'Monrovia', 'AF'),
      array('132', 'Lesotho', 'LS', 'LSO', '426', 'Maseru', 'AF'),
      array('132', 'Lesotho', 'LS', 'LSO', '426', 'Maseru', 'AF'),
      array('133', 'Lithuania', 'LT', 'LTU', '440', 'Vilnius', 'EU'),
      array('133', 'Lithuania', 'LT', 'LTU', '440', 'Vilnius', 'EU'),
      array('134', 'Luxembourg', 'LU', 'LUX', '442', 'Luxembourg', 'EU'),
      array('134', 'Luxembourg', 'LU', 'LUX', '442', 'Luxembourg', 'EU'),
      array('135', 'Latvia', 'LV', 'LVA', '428', 'Riga', 'EU'),
      array('135', 'Latvia', 'LV', 'LVA', '428', 'Riga', 'EU'),
      array('136', 'Libya', 'LY', 'LBY', '434', 'Tripoli', 'AF'),
      array('136', 'Libya', 'LY', 'LBY', '434', 'Tripoli', 'AF'),
      array('137', 'Morocco', 'MA', 'MAR', '504', 'Rabat', 'AF'),
      array('137', 'Morocco', 'MA', 'MAR', '504', 'Rabat', 'AF'),
      array('138', 'Monaco', 'MC', 'MCO', '492', 'Monaco', 'EU'),
      array('138', 'Monaco', 'MC', 'MCO', '492', 'Monaco', 'EU'),
      array('139', 'Moldova', 'MD', 'MDA', '498', 'Chisinau', 'EU'),
      array('139', 'Moldova', 'MD', 'MDA', '498', 'Chisinau', 'EU'),
      array('140', 'Montenegro', 'ME', 'MNE', '499', 'Podgorica', 'EU'),
      array('140', 'Montenegro', 'ME', 'MNE', '499', 'Podgorica', 'EU'),
      array('141', 'Saint Martin', 'MF', 'MAF', '663', 'Marigot', 'NA'),
      array('141', 'Saint Martin', 'MF', 'MAF', '663', 'Marigot', 'NA'),
      array('142', 'Madagascar', 'MG', 'MDG', '450', 'Antananarivo', 'AF'),
      array('142', 'Madagascar', 'MG', 'MDG', '450', 'Antananarivo', 'AF'),
      array('143', 'Marshall Islands', 'MH', 'MHL', '584', 'Majuro', 'OC'),
      array('143', 'Marshall Islands', 'MH', 'MHL', '584', 'Majuro', 'OC'),
      array('144', 'North Macedonia', 'MK', 'MKD', '807', 'Skopje', 'EU'),
      array('144', 'North Macedonia', 'MK', 'MKD', '807', 'Skopje', 'EU'),
      array('145', 'Mali', 'ML', 'MLI', '466', 'Bamako', 'AF'),
      array('145', 'Mali', 'ML', 'MLI', '466', 'Bamako', 'AF'),
      array('146', 'Myanmar', 'MM', 'MMR', '104', 'Nay Pyi Taw', 'AS'),
      array('146', 'Myanmar', 'MM', 'MMR', '104', 'Nay Pyi Taw', 'AS'),
      array('147', 'Mongolia', 'MN', 'MNG', '496', 'Ulaanbaatar', 'AS'),
      array('147', 'Mongolia', 'MN', 'MNG', '496', 'Ulaanbaatar', 'AS'),
      array('148', 'Macao', 'MO', 'MAC', '446', 'Macao', 'AS'),
      array('148', 'Macao', 'MO', 'MAC', '446', 'Macao', 'AS'),
      array('149', 'Northern Mariana Islands', 'MP', 'MNP', '580', 'Saipan', 'OC'),
      array('149', 'Northern Mariana Islands', 'MP', 'MNP', '580', 'Saipan', 'OC'),
      array('150', 'Martinique', 'MQ', 'MTQ', '474', 'Fort-de-France', 'NA'),
      array('150', 'Martinique', 'MQ', 'MTQ', '474', 'Fort-de-France', 'NA'),
      array('151', 'Mauritania', 'MR', 'MRT', '478', 'Nouakchott', 'AF'),
      array('151', 'Mauritania', 'MR', 'MRT', '478', 'Nouakchott', 'AF'),
      array('152', 'Montserrat', 'MS', 'MSR', '500', 'Plymouth', 'NA'),
      array('152', 'Montserrat', 'MS', 'MSR', '500', 'Plymouth', 'NA'),
      array('153', 'Malta', 'MT', 'MLT', '470', 'Valletta', 'EU'),
      array('153', 'Malta', 'MT', 'MLT', '470', 'Valletta', 'EU'),
      array('154', 'Mauritius', 'MU', 'MUS', '480', 'Port Louis', 'AF'),
      array('154', 'Mauritius', 'MU', 'MUS', '480', 'Port Louis', 'AF'),
      array('155', 'Maldives', 'MV', 'MDV', '462', 'Male', 'AS'),
      array('155', 'Maldives', 'MV', 'MDV', '462', 'Male', 'AS'),
      array('156', 'Malawi', 'MW', 'MWI', '454', 'Lilongwe', 'AF'),
      array('156', 'Malawi', 'MW', 'MWI', '454', 'Lilongwe', 'AF'),
      array('157', 'Mexico', 'MX', 'MEX', '484', 'Mexico City', 'NA'),
      array('157', 'Mexico', 'MX', 'MEX', '484', 'Mexico City', 'NA'),
      array('158', 'Malaysia', 'MY', 'MYS', '458', 'Kuala Lumpur', 'AS'),
      array('158', 'Malaysia', 'MY', 'MYS', '458', 'Kuala Lumpur', 'AS'),
      array('159', 'Mozambique', 'MZ', 'MOZ', '508', 'Maputo', 'AF'),
      array('159', 'Mozambique', 'MZ', 'MOZ', '508', 'Maputo', 'AF'),
      array('160', 'Namibia', 'NA', 'NAM', '516', 'Windhoek', 'AF'),
      array('160', 'Namibia', 'NA', 'NAM', '516', 'Windhoek', 'AF'),
      array('161', 'New Caledonia', 'NC', 'NCL', '540', 'Noumea', 'OC'),
      array('161', 'New Caledonia', 'NC', 'NCL', '540', 'Noumea', 'OC'),
      array('162', 'Niger', 'NE', 'NER', '562', 'Niamey', 'AF'),
      array('162', 'Niger', 'NE', 'NER', '562', 'Niamey', 'AF'),
      array('163', 'Norfolk Island', 'NF', 'NFK', '574', 'Kingston', 'OC'),
      array('163', 'Norfolk Island', 'NF', 'NFK', '574', 'Kingston', 'OC'),
      array('164', 'Nigeria', 'NG', 'NGA', '566', 'Abuja', 'AF'),
      array('164', 'Nigeria', 'NG', 'NGA', '566', 'Abuja', 'AF'),
      array('165', 'Nicaragua', 'NI', 'NIC', '558', 'Managua', 'NA'),
      array('165', 'Nicaragua', 'NI', 'NIC', '558', 'Managua', 'NA'),
      array('166', 'Netherlands', 'NL', 'NLD', '528', 'Amsterdam', 'EU'),
      array('166', 'Netherlands', 'NL', 'NLD', '528', 'Amsterdam', 'EU'),
      array('167', 'Norway', 'NO', 'NOR', '578', 'Oslo', 'EU'),
      array('167', 'Norway', 'NO', 'NOR', '578', 'Oslo', 'EU'),
      array('168', 'Nepal', 'NP', 'NPL', '524', 'Kathmandu', 'AS'),
      array('168', 'Nepal', 'NP', 'NPL', '524', 'Kathmandu', 'AS'),
      array('169', 'Nauru', 'NR', 'NRU', '520', 'Yaren', 'OC'),
      array('169', 'Nauru', 'NR', 'NRU', '520', 'Yaren', 'OC'),
      array('170', 'Niue', 'NU', 'NIU', '570', 'Alofi', 'OC'),
      array('170', 'Niue', 'NU', 'NIU', '570', 'Alofi', 'OC'),
      array('171', 'New Zealand', 'NZ', 'NZL', '554', 'Wellington', 'OC'),
      array('171', 'New Zealand', 'NZ', 'NZL', '554', 'Wellington', 'OC'),
      array('172', 'Oman', 'OM', 'OMN', '512', 'Muscat', 'AS'),
      array('172', 'Oman', 'OM', 'OMN', '512', 'Muscat', 'AS'),
      array('173', 'Panama', 'PA', 'PAN', '591', 'Panama City', 'NA'),
      array('173', 'Panama', 'PA', 'PAN', '591', 'Panama City', 'NA'),
      array('174', 'Peru', 'PE', 'PER', '604', 'Lima', 'SA'),
      array('174', 'Peru', 'PE', 'PER', '604', 'Lima', 'SA'),
      array('175', 'French Polynesia', 'PF', 'PYF', '258', 'Papeete', 'OC'),
      array('175', 'French Polynesia', 'PF', 'PYF', '258', 'Papeete', 'OC'),
      array('176', 'Papua New Guinea', 'PG', 'PNG', '598', 'Port Moresby', 'OC'),
      array('176', 'Papua New Guinea', 'PG', 'PNG', '598', 'Port Moresby', 'OC'),
      array('177', 'Philippines', 'PH', 'PHL', '608', 'Manila', 'AS'),
      array('177', 'Philippines', 'PH', 'PHL', '608', 'Manila', 'AS'),
      array('178', 'Pakistan', 'PK', 'PAK', '586', 'Islamabad', 'AS'),
      array('178', 'Pakistan', 'PK', 'PAK', '586', 'Islamabad', 'AS'),
      array('179', 'Poland', 'PL', 'POL', '616', 'Warsaw', 'EU'),
      array('179', 'Poland', 'PL', 'POL', '616', 'Warsaw', 'EU'),
      array('180', 'Saint Pierre and Miquelon', 'PM', 'SPM', '666', 'Saint-Pierre', 'NA'),
      array('180', 'Saint Pierre and Miquelon', 'PM', 'SPM', '666', 'Saint-Pierre', 'NA'),
      array('181', 'Pitcairn Islands', 'PN', 'PCN', '612', 'Adamstown', 'OC'),
      array('181', 'Pitcairn Islands', 'PN', 'PCN', '612', 'Adamstown', 'OC'),
      array('182', 'Puerto Rico', 'PR', 'PRI', '630', 'San Juan', 'NA'),
      array('182', 'Puerto Rico', 'PR', 'PRI', '630', 'San Juan', 'NA'),
      array('183', 'Palestine', 'PS', 'PSE', '275', 'East Jerusalem', 'AS'),
      array('183', 'Palestine', 'PS', 'PSE', '275', 'East Jerusalem', 'AS'),
      array('184', 'Portugal', 'PT', 'PRT', '620', 'Lisbon', 'EU'),
      array('184', 'Portugal', 'PT', 'PRT', '620', 'Lisbon', 'EU'),
      array('185', 'Palau', 'PW', 'PLW', '585', 'Melekeok', 'OC'),
      array('185', 'Palau', 'PW', 'PLW', '585', 'Melekeok', 'OC'),
      array('186', 'Paraguay', 'PY', 'PRY', '600', 'Asuncion', 'SA'),
      array('186', 'Paraguay', 'PY', 'PRY', '600', 'Asuncion', 'SA'),
      array('187', 'Qatar', 'QA', 'QAT', '634', 'Doha', 'AS'),
      array('187', 'Qatar', 'QA', 'QAT', '634', 'Doha', 'AS'),
      array('188', 'R?union', 'RE', 'REU', '638', 'Saint-Denis', 'AF'),
      array('188', 'R?union', 'RE', 'REU', '638', 'Saint-Denis', 'AF'),
      array('189', 'Romania', 'RO', 'ROU', '642', 'Bucharest', 'EU'),
      array('189', 'Romania', 'RO', 'ROU', '642', 'Bucharest', 'EU'),
      array('190', 'Serbia', 'RS', 'SRB', '688', 'Belgrade', 'EU'),
      array('190', 'Serbia', 'RS', 'SRB', '688', 'Belgrade', 'EU'),
      array('191', 'Russia', 'RU', 'RUS', '643', 'Moscow', 'EU'),
      array('191', 'Russia', 'RU', 'RUS', '643', 'Moscow', 'EU'),
      array('192', 'Rwanda', 'RW', 'RWA', '646', 'Kigali', 'AF'),
      array('192', 'Rwanda', 'RW', 'RWA', '646', 'Kigali', 'AF'),
      array('193', 'Saudi Arabia', 'SA', 'SAU', '682', 'Riyadh', 'AS'),
      array('193', 'Saudi Arabia', 'SA', 'SAU', '682', 'Riyadh', 'AS'),
      array('194', 'Solomon Islands', 'SB', 'SLB', '90', 'Honiara', 'OC'),
      array('194', 'Solomon Islands', 'SB', 'SLB', '90', 'Honiara', 'OC'),
      array('195', 'Seychelles', 'SC', 'SYC', '690', 'Victoria', 'AF'),
      array('195', 'Seychelles', 'SC', 'SYC', '690', 'Victoria', 'AF'),
      array('196', 'Sudan', 'SD', 'SDN', '729', 'Khartoum', 'AF'),
      array('196', 'Sudan', 'SD', 'SDN', '729', 'Khartoum', 'AF'),
      array('197', 'Sweden', 'SE', 'SWE', '752', 'Stockholm', 'EU'),
      array('197', 'Sweden', 'SE', 'SWE', '752', 'Stockholm', 'EU'),
      array('198', 'Singapore', 'SG', 'SGP', '702', 'Singapore', 'AS'),
      array('198', 'Singapore', 'SG', 'SGP', '702', 'Singapore', 'AS'),
      array('199', 'Saint Helena', 'SH', 'SHN', '654', 'Jamestown', 'AF'),
      array('199', 'Saint Helena', 'SH', 'SHN', '654', 'Jamestown', 'AF'),
      array('200', 'Slovenia', 'SI', 'SVN', '705', 'Ljubljana', 'EU'),
      array('200', 'Slovenia', 'SI', 'SVN', '705', 'Ljubljana', 'EU'),
      array('201', 'Svalbard and Jan Mayen', 'SJ', 'SJM', '744', 'Longyearbyen', 'EU'),
      array('201', 'Svalbard and Jan Mayen', 'SJ', 'SJM', '744', 'Longyearbyen', 'EU'),
      array('202', 'Slovakia', 'SK', 'SVK', '703', 'Bratislava', 'EU'),
      array('202', 'Slovakia', 'SK', 'SVK', '703', 'Bratislava', 'EU'),
      array('203', 'Sierra Leone', 'SL', 'SLE', '694', 'Freetown', 'AF'),
      array('203', 'Sierra Leone', 'SL', 'SLE', '694', 'Freetown', 'AF'),
      array('204', 'San Marino', 'SM', 'SMR', '674', 'San Marino', 'EU'),
      array('204', 'San Marino', 'SM', 'SMR', '674', 'San Marino', 'EU'),
      array('205', 'Senegal', 'SN', 'SEN', '686', 'Dakar', 'AF'),
      array('205', 'Senegal', 'SN', 'SEN', '686', 'Dakar', 'AF'),
      array('206', 'Somalia', 'SO', 'SOM', '706', 'Mogadishu', 'AF'),
      array('206', 'Somalia', 'SO', 'SOM', '706', 'Mogadishu', 'AF'),
      array('207', 'Suriname', 'SR', 'SUR', '740', 'Paramaribo', 'SA'),
      array('207', 'Suriname', 'SR', 'SUR', '740', 'Paramaribo', 'SA'),
      array('208', 'South Sudan', 'SS', 'SSD', '728', 'Juba', 'AF'),
      array('208', 'South Sudan', 'SS', 'SSD', '728', 'Juba', 'AF'),
      array('209', 'S?o Tom? and Pr?ncipe', 'ST', 'STP', '678', 'Sao Tome', 'AF'),
      array('209', 'S?o Tom? and Pr?ncipe', 'ST', 'STP', '678', 'Sao Tome', 'AF'),
      array('210', 'El Salvador', 'SV', 'SLV', '222', 'San Salvador', 'NA'),
      array('210', 'El Salvador', 'SV', 'SLV', '222', 'San Salvador', 'NA'),
      array('211', 'Sint Maarten', 'SX', 'SXM', '534', 'Philipsburg', 'NA'),
      array('211', 'Sint Maarten', 'SX', 'SXM', '534', 'Philipsburg', 'NA'),
      array('212', 'Syria', 'SY', 'SYR', '760', 'Damascus', 'AS'),
      array('212', 'Syria', 'SY', 'SYR', '760', 'Damascus', 'AS'),
      array('213', 'Eswatini', 'SZ', 'SWZ', '748', 'Mbabane', 'AF'),
      array('213', 'Eswatini', 'SZ', 'SWZ', '748', 'Mbabane', 'AF'),
      array('214', 'Turks and Caicos Islands', 'TC', 'TCA', '796', 'Cockburn Town', 'NA'),
      array('214', 'Turks and Caicos Islands', 'TC', 'TCA', '796', 'Cockburn Town', 'NA'),
      array('215', 'Chad', 'TD', 'TCD', '148', 'N`Djamena', 'AF'),
      array('215', 'Chad', 'TD', 'TCD', '148', 'N`Djamena', 'AF'),
      array('216', 'French Southern Territories', 'TF', 'ATF', '260', 'Port-aux-Francais', 'AN'),
      array('216', 'French Southern Territories', 'TF', 'ATF', '260', 'Port-aux-Francais', 'AN'),
      array('217', 'Togo', 'TG', 'TGO', '768', 'Lome', 'AF'),
      array('217', 'Togo', 'TG', 'TGO', '768', 'Lome', 'AF'),
      array('218', 'Thailand', 'TH', 'THA', '764', 'Bangkok', 'AS'),
      array('218', 'Thailand', 'TH', 'THA', '764', 'Bangkok', 'AS'),
      array('219', 'Tajikistan', 'TJ', 'TJK', '762', 'Dushanbe', 'AS'),
      array('219', 'Tajikistan', 'TJ', 'TJK', '762', 'Dushanbe', 'AS'),
      array('220', 'Tokelau', 'TK', 'TKL', '772', 'Tokelau', 'OC'),
      array('220', 'Tokelau', 'TK', 'TKL', '772', 'Tokelau', 'OC'),
      array('221', 'Timor-Leste', 'TL', 'TLS', '626', 'Dili', 'OC'),
      array('221', 'Timor-Leste', 'TL', 'TLS', '626', 'Dili', 'OC'),
      array('222', 'Turkmenistan', 'TM', 'TKM', '795', 'Ashgabat', 'AS'),
      array('222', 'Turkmenistan', 'TM', 'TKM', '795', 'Ashgabat', 'AS'),
      array('223', 'Tunisia', 'TN', 'TUN', '788', 'Tunis', 'AF'),
      array('223', 'Tunisia', 'TN', 'TUN', '788', 'Tunis', 'AF'),
      array('224', 'Tonga', 'TO', 'TON', '776', 'Nuku`alofa', 'OC'),
      array('224', 'Tonga', 'TO', 'TON', '776', 'Nuku`alofa', 'OC'),
      array('225', 'Turkey', 'TR', 'TUR', '792', 'Ankara', 'AS'),
      array('225', 'Turkey', 'TR', 'TUR', '792', 'Ankara', 'AS'),
      array('226', 'Trinidad and Tobago', 'TT', 'TTO', '780', 'Port of Spain', 'NA'),
      array('226', 'Trinidad and Tobago', 'TT', 'TTO', '780', 'Port of Spain', 'NA'),
      array('227', 'Tuvalu', 'TV', 'TUV', '798', 'Funafuti', 'OC'),
      array('227', 'Tuvalu', 'TV', 'TUV', '798', 'Funafuti', 'OC'),
      array('228', 'Taiwan', 'TW', 'TWN', '158', 'Taipei', 'AS'),
      array('228', 'Taiwan', 'TW', 'TWN', '158', 'Taipei', 'AS'),
      array('229', 'Tanzania', 'TZ', 'TZA', '834', 'Dodoma', 'AF'),
      array('229', 'Tanzania', 'TZ', 'TZA', '834', 'Dodoma', 'AF'),
      array('230', 'Ukraine', 'UA', 'UKR', '804', 'Kyiv', 'EU'),
      array('230', 'Ukraine', 'UA', 'UKR', '804', 'Kyiv', 'EU'),
      array('231', 'Uganda', 'UG', 'UGA', '800', 'Kampala', 'AF'),
      array('231', 'Uganda', 'UG', 'UGA', '800', 'Kampala', 'AF'),
      array('232', 'United States', 'US', 'USA', '840', 'Washington', 'NA'),
      array('232', 'United States', 'US', 'USA', '840', 'Washington', 'NA'),
      array('233', 'Uruguay', 'UY', 'URY', '858', 'Montevideo', 'SA'),
      array('233', 'Uruguay', 'UY', 'URY', '858', 'Montevideo', 'SA'),
      array('234', 'Uzbekistan', 'UZ', 'UZB', '860', 'Tashkent', 'AS'),
      array('234', 'Uzbekistan', 'UZ', 'UZB', '860', 'Tashkent', 'AS'),
      array('235', 'Vatican City', 'VA', 'VAT', '336', 'Vatican City', 'EU'),
      array('235', 'Vatican City', 'VA', 'VAT', '336', 'Vatican City', 'EU'),
      array('236', 'St Vincent and Grenadines', 'VC', 'VCT', '670', 'Kingstown', 'NA'),
      array('236', 'St Vincent and Grenadines', 'VC', 'VCT', '670', 'Kingstown', 'NA'),
      array('237', 'Venezuela', 'VE', 'VEN', '862', 'Caracas', 'SA'),
      array('237', 'Venezuela', 'VE', 'VEN', '862', 'Caracas', 'SA'),
      array('238', 'British Virgin Islands', 'VG', 'VGB', '92', 'Road Town', 'NA'),
      array('238', 'British Virgin Islands', 'VG', 'VGB', '92', 'Road Town', 'NA'),
      array('239', 'U.S. Virgin Islands', 'VI', 'VIR', '850', 'Charlotte Amalie', 'NA'),
      array('239', 'U.S. Virgin Islands', 'VI', 'VIR', '850', 'Charlotte Amalie', 'NA'),
      array('240', 'Vietnam', 'VN', 'VNM', '704', 'Hanoi', 'AS'),
      array('240', 'Vietnam', 'VN', 'VNM', '704', 'Hanoi', 'AS'),
      array('241', 'Vanuatu', 'VU', 'VUT', '548', 'Port Vila', 'OC'),
      array('241', 'Vanuatu', 'VU', 'VUT', '548', 'Port Vila', 'OC'),
      array('242', 'Wallis and Futuna', 'WF', 'WLF', '876', 'Mata Utu', 'OC'),
      array('242', 'Wallis and Futuna', 'WF', 'WLF', '876', 'Mata Utu', 'OC'),
      array('243', 'Samoa', 'WS', 'WSM', '882', 'Apia', 'OC'),
      array('243', 'Samoa', 'WS', 'WSM', '882', 'Apia', 'OC'),
      array('244', 'Kosovo', 'XK', 'XKX', '0', 'Pristina', 'EU'),
      array('244', 'Kosovo', 'XK', 'XKX', '0', 'Pristina', 'EU'),
      array('245', 'Yemen', 'YE', 'YEM', '887', 'Sanaa', 'AS'),
      array('245', 'Yemen', 'YE', 'YEM', '887', 'Sanaa', 'AS'),
      array('246', 'Mayotte', 'YT', 'MYT', '175', 'Mamoudzou', 'AF'),
      array('246', 'Mayotte', 'YT', 'MYT', '175', 'Mamoudzou', 'AF'),
      array('247', 'South Africa', 'ZA', 'ZAF', '710', 'Pretoria', 'AF'),
      array('247', 'South Africa', 'ZA', 'ZAF', '710', 'Pretoria', 'AF'),
      array('248', 'Zambia', 'ZM', 'ZMB', '894', 'Lusaka', 'AF'),
      array('248', 'Zambia', 'ZM', 'ZMB', '894', 'Lusaka', 'AF'),
      array('249', 'Zimbabwe', 'ZW', 'ZWE', '716', 'Harare', 'AF'),
      array('249', 'Zimbabwe', 'ZW', 'ZWE', '716', 'Harare', 'AF'),
    ),
    'mr_language' => array(
      array('id' => '1', 'Name' => 'RU', 'Description' => 'Русский'),
      array('id' => '2', 'Name' => 'EN', 'Description' => 'English')
    ),
  );
}